name: CD
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  buildImageAndDeploy:
    name: BuildImageAndDeploy
    timeoutInMinutes: 5
    steps:
      - checkout: self
      - task: Bash@3
        inputs:
          filePath: pipeline/build.sh
          workingDirectory: $(Build.SourcesDirectory)/services/aqueduct_artiq_data_processing
          displayName: "Build Image"

      - task: Bash@3
        inputs:
          filePath: pipeline/deploy.prod.sh
          workingDirectory: $(Build.SourcesDirectory)/services/aqueduct_artiq_data_processing
          displayName: "Pod deployments"
