name: CD
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  buildImageAndDeploy:
    name: BuildImageAndDeploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Image
        run: |
          chmod +x ./pipeline/build.sh
          ./pipeline/build.sh

      - name: Deploy instance
        run: |
          chmod +x ./pipeline/deploy.prod.sh
          ./pipeline/deploy.prod.sh
